import {Module} from "vuex";

interface textState{
	text: string,
	fontFamily: string,
	fontSize: number,
	fontStyle: string,
	textDecoration: string,
	align: string,
	fill: string,
	fillEnabled: boolean,
	stroke: string,
	strokeEnabled: boolean,
	strokeWidth: number,
	shadowColor: string,
	shadowEnabled: boolean,
	shadowBlur: number,
	shadowOffsetX: number,
	shadowOffsetY: number,
	opacity: number,
	rotation: number,
}
const TextState:Module<textState, any>={
	namespaced: true,
	state:{
		text:"Текст",
		fontFamily: "Cambria",
		fontSize: 50,
		fontStyle: "",
		textDecoration:"",
		align: "left",
		fill: "#ffffff",
		fillEnabled: true,
		stroke:"#000000",
		strokeEnabled:true,
		strokeWidth: 1,
		shadowColor: "#000000",
		shadowEnabled: false,
		shadowBlur: 1,
		shadowOffsetX: 1,
		shadowOffsetY: 1,
		opacity: 1,
		rotation: 1
	},
	getters:{
		getTextOptions:(state):textState=>state,
		getText:(state):string=>state.text,
		getFontFamily:(state):string=>state.fontFamily,
		getFontSize:(state):number=>state.fontSize,
		getFontStyle:(state):string=>state.fontStyle,
		getTextDecoration:(state):string=>state.textDecoration,
		getAlign:(state):string=>state.align,
		getFillColor:(state):string=>state.fill,
		getFillEnabled:(state):boolean=>state.fillEnabled,
		getStrokeColor:(state):string=>state.stroke,
		getStrokeWidth:(state):number=>state.strokeWidth,
		getStrokeEnabled:(state):boolean=>state.strokeEnabled,
		getShadowColor:(state):string=>state.shadowColor,
		getShadowEnabled:(state):boolean=>state.shadowEnabled,
		getShadowBlur:(state):number=>state.shadowBlur,
		getShadowOffsetX:(state):number=>state.shadowOffsetX,
		getShadowOffsetY:(state):number=>state.shadowOffsetY,
		getOpacity:(state):number=>state.opacity,
		getRotation:(state):number=>state.rotation
	},
	mutations:{
		setText:(state, value:string)=>state.text = value,
		setFontFamily:(state, value:string)=>state.fontFamily = value,
		setFontSize:(state, value:number)=>state.fontSize = value,
		setFontStyle:(state, value:string)=>state.fontStyle = value,
		setTextDecoration:(state, value:string)=>state.textDecoration = value,
		setAlign:(state, value:string)=>state.align = value,
		setFillColor:(state, value:string)=>state.fill = value,
		setFillEnabled:(state, value:boolean)=>state.fillEnabled = value,
		setStrokeColor:(state, value:string)=>state.stroke = value,
		setStrokeWidth:(state, value:number)=>state.strokeWidth = value,
		setStrokeEnabled:(state, value:boolean)=>state.strokeEnabled = value,
		setShadowColor:(state, value:string)=>state.shadowColor = value,
		setShadowEnabled:(state, value:boolean)=>state.shadowEnabled = value,
		setShadowBlur:(state, value:number)=>state.shadowBlur = value,
		setShadowOffsetX:(state, value:number)=>state.shadowOffsetX = value,
		setShadowOffsetY:(state, value:number)=>state.shadowOffsetY = value,
		setOpacity:(state, value:number)=>state.opacity = value,
		setRotation:(state, value:number)=>state.rotation = value
	}
}

export default TextState
